web: Include authors on each page
plt-amy/cubical-1lab pull request #31
Opened 2022-01-31 20:56 UTC by SquidDev

Adds a "Written by: xyz" section to each page:

![A screenshot of 1Lab.Path, with 'Written by Amélia Liao, Astra Kolomatskaia, Jonathan Coates and uni' on the bottom left](https://user-images.githubusercontent.com/4346137/151871697-a24cbc36-1142-4f33-8a44-e2c7d082eef4.png).

It's a little dubious (git log isn't smart enough to exclude whitespace changes), but good enough. I think!

2022-01-31 20:57 UTC, plt-amy commented
🎉

2022-01-31 21:00 UTC, plt-amy requested changes

2022-01-31 21:00 UTC, plt-amy commented on src/index.lagda.md
> +here](1Lab.Intro.html)**.
What happened here?

2022-02-01 10:53 UTC, SquidDev commented on src/index.lagda.md
> +here](1Lab.Intro.html)**.
I also noticed the link to 1lab instead of 1Lab, but fixed the wrong thing instead. I cannot explain myself.

2022-02-01 17:16 UTC, plt-amy commented on src/index.lagda.md
> +here](1Lab.Intro.html)**.
haha

2022-02-04 23:28 UTC, merged